// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteRelationValue(arg1:string):Promise<void>;

export function GetAllObjectsSimple():Promise<Array<main.ObjectEntity>>;

export function GetAllRelationsTypes():Promise<Array<main.RelationTypeEntity>>;

export function GetGraphNetwork(arg1:boolean,arg2:number):Promise<main.GraphData>;

export function GetParametersForTarget(arg1:string):Promise<Array<main.ParameterValueEntity>>;

export function GetRelationsForTarget(arg1:string):Promise<Array<main.RelationValueEntity>>;

export function GetTreeForNode(arg1:string,arg2:number,arg3:number):Promise<main.TreeNodeData>;

export function SaveParameterValue(arg1:main.ParameterValueEntity):Promise<void>;

export function SaveRelationValue(arg1:main.RelationValueEntity):Promise<void>;

export function SearchNodesForSelect(arg1:string,arg2:number):Promise<Array<main.ObjectEntity>>;

export function SearchParametersForSelect(arg1:string):Promise<Array<main.ParameterDefinition>>;

export function UpdateObject(arg1:main.ObjectEntity):Promise<void>;
