// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRelationValue(arg1) {
  return window['go']['main']['App']['DeleteRelationValue'](arg1);
}

export function ExecuteMediaImport(arg1, arg2) {
  return window['go']['main']['App']['ExecuteMediaImport'](arg1, arg2);
}

export function GetAllObjectsSimple() {
  return window['go']['main']['App']['GetAllObjectsSimple']();
}

export function GetAllRelationsTypes() {
  return window['go']['main']['App']['GetAllRelationsTypes']();
}

export function GetGraphNetwork(arg1, arg2) {
  return window['go']['main']['App']['GetGraphNetwork'](arg1, arg2);
}

export function GetParametersForTarget(arg1) {
  return window['go']['main']['App']['GetParametersForTarget'](arg1);
}

export function GetRelationsForTarget(arg1) {
  return window['go']['main']['App']['GetRelationsForTarget'](arg1);
}

export function GetTreeForNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTreeForNode'](arg1, arg2, arg3);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function SaveParameterValue(arg1) {
  return window['go']['main']['App']['SaveParameterValue'](arg1);
}

export function SaveRelationValue(arg1) {
  return window['go']['main']['App']['SaveRelationValue'](arg1);
}

export function ScanMediaDirectory(arg1) {
  return window['go']['main']['App']['ScanMediaDirectory'](arg1);
}

export function SearchNodesForSelect(arg1, arg2) {
  return window['go']['main']['App']['SearchNodesForSelect'](arg1, arg2);
}

export function SearchParametersForSelect(arg1) {
  return window['go']['main']['App']['SearchParametersForSelect'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UpdateObject(arg1) {
  return window['go']['main']['App']['UpdateObject'](arg1);
}
