// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNewObject(arg1:string,arg2:string):Promise<string>;

export function DeleteRelationValue(arg1:string):Promise<void>;

export function ExecuteBatchInsertWithUUIDv7(arg1:string,arg2:number):Promise<main.SQLExecutionResult>;

export function ExecuteGenericInsertWithUUIDv7(arg1:string):Promise<main.SQLExecutionResult>;

export function ExecuteMediaImport(arg1:string,arg2:string,arg3:string,arg4:Array<main.MediaImportItem>):Promise<void>;

export function ExportBookReportToHTML(arg1:string,arg2:number,arg3:string):Promise<string>;

export function ExportBookReportToPDF(arg1:string,arg2:number,arg3:string):Promise<string>;

export function ExportReportToPDF(arg1:main.ReportTreeNode,arg2:string):Promise<void>;

export function FetchReportTree(arg1:string,arg2:number,arg3:string):Promise<main.ReportTreeNode>;

export function GenerateBookReport(arg1:string,arg2:number,arg3:string):Promise<string>;

export function GenerateSingleUUIDv7():Promise<string>;

export function GetAllMasterParameters():Promise<Array<main.ParameterMaster>>;

export function GetAllMasterRelations():Promise<Array<main.RelationMaster>>;

export function GetAllMasterUnits():Promise<Array<main.UnitMaster>>;

export function GetAllObjectsSimple():Promise<Array<main.ObjectEntity>>;

export function GetAllRelationsTypes():Promise<Array<main.RelationTypeEntity>>;

export function GetGraphNetwork(arg1:boolean,arg2:number):Promise<main.GraphData>;

export function GetLocalImageBase64(arg1:string):Promise<string>;

export function GetObjectById(arg1:string):Promise<main.ObjectEntity>;

export function GetObjectTree(arg1:string,arg2:number):Promise<main.GraphNode>;

export function GetObjectTypes():Promise<Array<main.ObjectTypeOption>>;

export function GetObjectsForSelect(arg1:string):Promise<Array<main.ObjectSelectItem>>;

export function GetObjectsForSelector():Promise<Array<main.SimpleObject>>;

export function GetParametersForTarget(arg1:string):Promise<Array<main.ParameterValueEntity>>;

export function GetParsedTemplateById(arg1:string):Promise<main.ReportTemplateConfig>;

export function GetRelationsForTarget(arg1:string):Promise<Array<main.RelationValueEntity>>;

export function GetTemplateById(arg1:string):Promise<main.DbTemplateRecord>;

export function GetTemplates():Promise<Array<main.DbTemplateRecord>>;

export function GetTreeForNode(arg1:string,arg2:number,arg3:number):Promise<main.TreeNodeData>;

export function OpenFile(arg1:string):Promise<void>;

export function PreviewSQLQuery(arg1:main.SQLQueryRequest):Promise<main.SQLQueryPreviewResult>;

export function ReindexOutgoingRelations(arg1:string):Promise<number>;

export function SaveMasterParameter(arg1:main.ParameterMaster):Promise<void>;

export function SaveMasterRelation(arg1:main.RelationMaster):Promise<void>;

export function SaveMasterUnit(arg1:main.UnitMaster):Promise<void>;

export function SaveParameterValue(arg1:main.ParameterValueEntity):Promise<void>;

export function SaveParsedTemplate(arg1:string,arg2:any,arg3:main.ReportTemplateConfig):Promise<void>;

export function SaveRelationValue(arg1:main.RelationValueEntity):Promise<void>;

export function SaveTemplateRecord(arg1:main.DbTemplateRecord):Promise<main.DbTemplateRecord>;

export function ScanMediaDirectory(arg1:string):Promise<Array<main.MediaImportItem>>;

export function SearchNodesForSelect(arg1:string,arg2:number):Promise<Array<main.ObjectEntity>>;

export function SearchParametersForSelect(arg1:string):Promise<Array<main.ParameterDefinition>>;

export function SelectDirectory():Promise<string>;

export function SelectImageFile():Promise<string>;

export function SelectSavePath(arg1:string):Promise<string>;

export function UpdateObject(arg1:main.ObjectEntity):Promise<void>;

export function V2_GenerateBookReport(arg1:string,arg2:string):Promise<string>;
