// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewObject(arg1, arg2) {
  return window['go']['main']['App']['CreateNewObject'](arg1, arg2);
}

export function DeleteRelationValue(arg1) {
  return window['go']['main']['App']['DeleteRelationValue'](arg1);
}

export function ExecuteMediaImport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteMediaImport'](arg1, arg2, arg3, arg4);
}

export function ExportBookReportToHTML(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportBookReportToHTML'](arg1, arg2, arg3);
}

export function ExportBookReportToPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportBookReportToPDF'](arg1, arg2, arg3);
}

export function ExportReportToPDF(arg1, arg2) {
  return window['go']['main']['App']['ExportReportToPDF'](arg1, arg2);
}

export function FetchReportTree(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchReportTree'](arg1, arg2, arg3);
}

export function GenerateBookReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateBookReport'](arg1, arg2, arg3);
}

export function GetAllObjectsSimple() {
  return window['go']['main']['App']['GetAllObjectsSimple']();
}

export function GetAllRelationsTypes() {
  return window['go']['main']['App']['GetAllRelationsTypes']();
}

export function GetGraphNetwork(arg1, arg2) {
  return window['go']['main']['App']['GetGraphNetwork'](arg1, arg2);
}

export function GetObjectTree(arg1, arg2) {
  return window['go']['main']['App']['GetObjectTree'](arg1, arg2);
}

export function GetObjectTypes() {
  return window['go']['main']['App']['GetObjectTypes']();
}

export function GetObjectsForSelect(arg1) {
  return window['go']['main']['App']['GetObjectsForSelect'](arg1);
}

export function GetObjectsForSelector() {
  return window['go']['main']['App']['GetObjectsForSelector']();
}

export function GetParametersForTarget(arg1) {
  return window['go']['main']['App']['GetParametersForTarget'](arg1);
}

export function GetParsedTemplateById(arg1) {
  return window['go']['main']['App']['GetParsedTemplateById'](arg1);
}

export function GetRelationsForTarget(arg1) {
  return window['go']['main']['App']['GetRelationsForTarget'](arg1);
}

export function GetTemplateById(arg1) {
  return window['go']['main']['App']['GetTemplateById'](arg1);
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetTreeForNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTreeForNode'](arg1, arg2, arg3);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function ReindexOutgoingRelations(arg1) {
  return window['go']['main']['App']['ReindexOutgoingRelations'](arg1);
}

export function SaveParameterValue(arg1) {
  return window['go']['main']['App']['SaveParameterValue'](arg1);
}

export function SaveParsedTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveParsedTemplate'](arg1, arg2, arg3);
}

export function SaveRelationValue(arg1) {
  return window['go']['main']['App']['SaveRelationValue'](arg1);
}

export function SaveTemplateRecord(arg1) {
  return window['go']['main']['App']['SaveTemplateRecord'](arg1);
}

export function ScanMediaDirectory(arg1) {
  return window['go']['main']['App']['ScanMediaDirectory'](arg1);
}

export function SearchNodesForSelect(arg1, arg2) {
  return window['go']['main']['App']['SearchNodesForSelect'](arg1, arg2);
}

export function SearchParametersForSelect(arg1) {
  return window['go']['main']['App']['SearchParametersForSelect'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectSavePath(arg1) {
  return window['go']['main']['App']['SelectSavePath'](arg1);
}

export function UpdateObject(arg1) {
  return window['go']['main']['App']['UpdateObject'](arg1);
}
